export TEST_ADMIN_CLIENTID=test9
 export TEST_ADMIN_CLIENTSECRET=Abcd1234
export TEST_ADMIN_USERNAME=test6
 export TEST_ADMIN_PASSWORD=Abcd1234
export TEST_APIHOST=api.127-0-0-1.nip.io
export TEST_SKIPSSLVALIDATION=true
export UAA_API_REQUEST_LIMIT=5

export CLIENT_LOGGING_LEVEL=debug
export TEST_LOGGING_LEVEL=debug